apiVersion: apps/v1
kind: Deployment
metadata:
  name: class-cicd-app
  labels:
    app: class-cicd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: class-cicd-app
  template:
    metadata:
      labels:
        app: class-cicd-app
    spec:
      containers:
      - name: class-cicd-app
        image: nginx:latest
        ports:
        - containerPort: 80
